### ISSUE TITLE
Mac Crashes when closing

### ISSUE THREAD

**Issue by Advik-B** [killpowa/Twickt-Launcher#1156]
**Describe the bug**
GDLaucher crashes when i try to close it

**To Reproduce**
1. Open GDLauncher
2. Click on close
3. Right click on the app and close it

**Expected behavior**
Closes the app

**Screenshots**

<img width="992" alt="Screenshot 2021-11-09 at 6 54 39 PM" src="https://user-images.githubusercontent.com/86160411/140932021-fc227e51-7194-4a6b-be47-668d62cef311.png">

**Operating System:**
- OS: Mac os
- Version: Mont-something
- Java Version: N/A
- Minecraft Version: N/A
- Mod Loader: N/A
- HardWare: Apple M1 pro

**Additional context**
Full log [here](https://gist.github.com/Advik-B/f2e3c23904fddcd832aad0cca649f9c5)

**Comment by Eskaan** [comment]
Could you please upload the log to a paste site?
Like https://gist.GitHub.com/
It’s really filling this up
Your OS is MacOS Monterey and you can see the Version by clicking on the Apple logo in the top bar and going on „About my Mac“ or so

**Comment by Advik-B** [comment]
> 
> 
> Could you please upload the log to a paste site? Like https://gist.GitHub.com/ It’s really filling this up Your OS is MacOS Monterey and you can see the Version by clicking on the Apple logo in the top bar and going on „About my Mac“ or so

Ok

**Comment by Advik-B** [comment]
@Code-Ac  the full log is [here](https://gist.github.com/Advik-B/f2e3c23904fddcd832aad0cca649f9c5)

**Comment by Eskaan** [comment]
Was it the First Time opening it?
Which version of the launcher do you have?
Are you on a new M1 Mac (because we don’t support that yet) :/

**Comment by Advik-B** [comment]
> 
> 
> Was it the First Time opening it? Which version of the launcher do you have? Are you on a new M1 Mac (because we don’t support that yet) :/

Yea I am on a M1 pro :-(

**Comment by Advik-B** [comment]
And this is not the first time i am running the app

**Comment by Advik-B** [comment]
I am on beta because of #1086 as suggested by @killpowa

**Comment by kyrtion** [comment]
> Are you on a new M1 Mac (because we don’t support that yet) :/

You can install virtual OS for testing

**Comment by jclendineng** [comment]
Any updates on this for the m1 Mac? MultiMC works fine

**Comment by Eskaan** [comment]
Sadly not in both issues. M1 still now supported and it still crashes when closing. At least I can reproduce it now (but I still don’t have any idea why). Will investigate when I have time but it’s a very slow process to restart and recompile it every time I want to try it.

**Comment by dstoliker** [comment]
Perhaps related to https://github.com/gorilla-devs/GDLauncher/issues/958

**Comment by Eskaan** [comment]
Yes it is (I reopened it now because I can reproduce it since v1.1.16)
(edit)
I am sorry for closing it in first place. I assume it was while I was scrolling older issues and closing the fixed ones

**Comment by huantianad** [comment]
Perhaps related to #1054 as well

**Comment by Eskaan** [comment]
Got this in the dev environment
```
(node:36556) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'dir' of 'T.package' as it is undefined.
    at Object.<anonymous> (/Users/kinder/Documents/GitHub/GDLauncher/build/electron.js:9392:1761)
    at Object../node_modules/esm/esm.js (/Users/kinder/Documents/GitHub/GDLauncher/build/electron.js:9393:30)
    at __webpack_require__ (/Users/kinder/Documents/GitHub/GDLauncher/build/electron.js:21:30)
    at closeServer (/Users/kinder/Documents/GitHub/GDLauncher/build/electron.js:29964:19)
    at App.<anonymous> (/Users/kinder/Documents/GitHub/GDLauncher/build/electron.js:30094:3)
    at App.emit (node:events:394:28)
    at click (/Users/kinder/Documents/GitHub/GDLauncher/build/electron.js:29834:11)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at Object.a._executeCommand (node:electron/js2c/browser_init:81:2453)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:36556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
GDL-S Request: {2 1639904161575-25ca08c173fd8 map[data:[123 125] type:Buffer]}

/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron[36556]: ../../third_party/electron_node/src/node_api.cc:1286:napi_status napi_release_threadsafe_function(napi_threadsafe_function, napi_threadsafe_function_release_mode): Assertion `(func) != nullptr' failed.
 1: 0x117edbad5 node::FatalException(v8::Isolate*, v8::TryCatch const&) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x117edb8af node::FatalException(v8::Isolate*, v8::TryCatch const&) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x117e8a44e napi_release_threadsafe_function [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x105dc10b0 NSFW::~NSFW() [/Users/kinder/Documents/GitHub/GDLauncher/build/native/darwin/nsfw.node]
 5: 0x105dc4f76 Napi::ObjectWrap<NSFW>::FinalizeCallback(napi_env__*, void*, void*) [/Users/kinder/Documents/GitHub/GDLauncher/build/native/darwin/nsfw.node]
 6: 0x117e8a7af node_api_get_module_file_name [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x117e7edaf node::AsyncResource::CallbackScope::CallbackScope(node::AsyncResource*) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x117e8a5e6 node_api_get_module_file_name [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x117e8b1e5 node_api_get_module_file_name [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x117e8b24e node_api_get_module_file_name [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x117e8b55b node_api_get_module_file_name [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x1110f1177 uv_run [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x117e6b9e4 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x117e6bef3 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x117e34fd4 node::FreeEnvironment(node::Environment*) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x1111efb95 ElectronInitializeICUandStartNode [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x1111d8099 ElectronInitializeICUandStartNode [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
18: 0x1134582f7 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
19: 0x113459c1a v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
20: 0x1134558e6 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
21: 0x1121bf8a3 cdef_copy_rect8_16bit_to_16bit_sse4_1 [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x1121bf33b cdef_copy_rect8_16bit_to_16bit_sse4_1 [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x1121bdd0b cdef_copy_rect8_16bit_to_16bit_sse4_1 [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
24: 0x1121be609 cdef_copy_rect8_16bit_to_16bit_sse4_1 [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x111102e06 ElectronMain [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
26: 0x1059a3d36  [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron]
27: 0x11103e4fe 
28: 0x0 
29: 0x1059a3000 __dso_handle [/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron]
/Users/kinder/Documents/GitHub/GDLauncher/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT

Process finished with exit code 1
```
Maybe someone can decrypt that

**Comment by jclendineng** [comment]
looks like an electron thing, possibly if electron is updated it will work, I know m1 has issues with electron still as far as I know so probably just a dependency issue.

**Comment by jclendineng** [comment]
Electron issue here:

https://github.com/electron/electron/issues/30786

We need to wait for a fix from them, it looks like electron is not m1 native yet (obviously, gdlauncher is slow as molasses on m1)
