### ISSUE TITLE
Fabric API Requires Java 17

### ISSUE THREAD

**Issue by SkyNinja** [killpowa/Twickt-Launcher#1192]
**Describe the bug**
The newest version of Fabric API, required for most Fabric installs, requires OpenJDK Server 17. GDLauncher provides version 16.

**To Reproduce**
1. Install a modern Fabric loader instance.
2. Install Fabric API.
3. Attempt to launch game.

**Stacktrace**
```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.44.0+1.18 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 16!
		 - 'OpenJDK 64-Bit Server VM' (java) 16 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'OpenJDK 64-Bit Server VM' (java) 16, reason: to replace
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.44.0+1.18 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 16!
		 - 'OpenJDK 64-Bit Server VM' (java) 16 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'OpenJDK 64-Bit Server VM' (java) 16, reason: to replace
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more
```

**Operating System:**
- OS: Windows
- Version: 10 21H1
- Java Version: 16
- Minecraft Version: 1.18
- Mod Loader: Fabric

**Additional context**

**Comment by SkyNinja** [comment]
Beta 3. Duh.
