### ISSUE TITLE
Cannot run any of my instances

### ISSUE THREAD

**Issue by rollingmoai** [killpowa/Twickt-Launcher#1206]
**Describe the bug**
None of my instances work at all (Fabric, Forge, Vanilla).

**To Reproduce**
1. Create an instance of any type (Fabric, Forge, Vanilla).
2. Run

**Expected behavior**
It launches.

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: 17

**Additional context**
Stacktrace:
```
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.needsLookupRemoval(Log4jLogHandler.java:91)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.<clinit>(Log4jLogHandler.java:80)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLog4jLogHandler(MinecraftGameProvider.java:515)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:229)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:172)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more
```

**Comment by FestplattenSchnitzel** [comment]
I also experienced this issue and it helped to delete all Java files installed by GDLauncher to trigger the automatic setup again (and create a new instance afterwards).

On Linux the Java files/directories are located at `~/.config/gdlauncher_next/java/`; not sure about Windows.

**Comment by rollingmoai** [comment]
> I also experienced this issue and it helped to delete all Java files installed by GDLauncher to trigger the automatic setup again (and create a new instance afterwards).
> 
> On Linux the Java files/directories are located at `~/.config/gdlauncher_next/java/`; not sure about Windows.

Didn't work for me unfortunately.

**Comment by rollingmoai** [comment]
Doing a complete reinstall of GDLauncher did the trick.
