### ISSUE TITLE
Can't open up links in-game

### ISSUE THREAD

**Issue by ItzYanick** [killpowa/Twickt-Launcher#1282]
**Describe the bug**
When clicking on a link and clicking "Yes" it does not open up a browser or a new browser tab.

**To Reproduce**
1. Join Server
2. Open a link window
3. Click Yes
4. Nothing happens

**Expected behavior**
A new browser tab should open with the link provided. If no browser is open it should open up a new browser.

**Operating System:**
- OS: Fedora 35
- Version: GDLauncher v1.1.21 - AppImage
- Java Version: 17
- Minecraft Version: 1.18.1
- Mod Loader: Fabric

**Additional context**
I uploaded the error message out of the log onto pastebin: https://pastebin.com/2DUCZW4v
I am thinking it might be due to the AppImage but I am not 100% sure

**Comment by MokahTGS** [comment]
Links also do not work from the launcher mod pages when managing mods.

**Comment by ItzYanick** [comment]
they work for me

**Comment by Baktus79** [comment]
Same here, but I dont think this is an GD Launcher issue, but the game itself on Linux.

**Comment by ItzYanick** [comment]
But Chromium etc can use xdg-open without any issues. So why would it work on Chromium and not on Minecraft? The Problem is I can't test it with the native minecraft launcher as it has no Fedora / RPM support sadly :(

**Comment by LordRaptorNinja** [comment]
I cant open links but I also cant open folders and stuff which is weird

**Comment by j-romchain** [comment]
I got a log of it from the launcher... [19:31:41] [IAS Executor/ERROR]: Couldn't open url 'https://login.live.com/oauth20_blahblahblah&prompt=select_account'
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_669(class_156.java:1127) ~[client-intermediary.jar:?]
	at net.minecraft.class_156$class_158.method_670(class_156.java:1183) ~[client-intermediary.jar:?]
	at the_fireplace.ias.gui.LoginScreen.lambda$loginMicrosoft$10(LoginScreen.java:94) ~[InGameAccountSwitcher-Fabric-1.19-8.0.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: Cannot run program "xdg-open": error=13, Permission denied
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:1129) ~[client-intermediary.jar:?]
	... 7 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:?]
	at java.lang.ProcessImpl.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:1129) ~[client-intermediary.jar:?]
	... 7 more

**Comment by j-romchain** [comment]
is it possibly a permission issue with not running as admin/not installing something as admin beforehand? I have also gotten errors from trying to change priority or somesuch and not having permission, but I assumed it was one of my mods...

**Comment by Eskaan** [comment]
This seems to be the relevant line:
```log
Caused by: java.io.IOException: Cannot run program "xdg-open": error=13, Permission denied
```
As it seems, the java instance does not have the privileges to open the external program which it should have.
`xdg-open` is the standard program to do such things like opening links/folders/files etc.

**Comment by j-romchain** [comment]
I am running this from the appimage, and anyway shouldn't it have the privileges already?

**Comment by Teapot4195** [comment]
Try extracting the appimage with --appimage-extract as a flag, and see if the issue persists outside of the appimage. Also had unexpected issues with my Linux install, but didn't even get that far because my system was more restrictive than default.

**Comment by j-romchain** [comment]
I ran this command and this was the log in the terminal, the links still didn't work, the other logs looked about the same...
Applications/GDLauncher-linux-setup_362c2a63c3aa5381e2aa0b885d47631f.AppImage --no-sandbox --appimage-extract
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
12:29:48.953 › setup 1.1.30
12:29:49.176 › Error: Command failed: chmod +x "/tmp/.mount_GDLaunzP9oOS/7za"
chmod: changing permissions of '/tmp/.mount_GDLaunzP9oOS/7za': Read-only file system

    at ChildProcess.exithandler (node:child_process:408:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[54029:0514/122953.399093:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[54029:0514/122953.399687:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
12:29:53.968 › Trying to start listener
12:29:53.970 › Started listener
12:29:54.233 › Unable to initialize Discord RPC: Error: Could not connect
    at Socket.r (/tmp/.mount_GDLaunzP9oOS/resources/app.asar/build/electron.js:2:43722)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Checking for update
Update for version 1.1.30 is not available (latest version: 1.1.30, downgrade is disallowed).
[54029:0514/122957.912482:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
(node:53981) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'write')
    at e.exports.send (/tmp/.mount_GDLaunzP9oOS/resources/app.asar/build/electron.js:2:45084)
    at /tmp/.mount_GDLaunzP9oOS/resources/app.asar/build/electron.js:2:33603
    at new Promise (<anonymous>)
    at e.exports.request (/tmp/.mount_GDLaunzP9oOS/resources/app.asar/build/electron.js:2:33555)
    at e.exports.setActivity (/tmp/.mount_GDLaunzP9oOS/resources/app.asar/build/electron.js:2:38035)
    at t.update (/tmp/.mount_GDLaunzP9oOS/resources/app.asar/build/electron.js:2:2722756)
    at /tmp/.mount_GDLaunzP9oOS/resources/app.asar/build/electron.js:2:2731028
    at node:electron/js2c/browser_init:189:579
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11327)
    at EventEmitter.emit (node:events:526:28)
(Use `gdlauncher --trace-warnings ...` to show where the warning was created)
(node:53981) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
12:30:01.157 › Detected 4 events from listener
12:30:02.257 › Detected 1 events from listener
12:30:02.757 › Detected 2 events from listener
12:30:07.965 › Detected 1 events from listener
12:30:08.465 › Detected 15 events from listener
12:30:08.965 › Detected 9 events from listener
12:30:10.617 › Detected 1 events from listener
12:30:11.118 › Detected 109 events from listener
12:30:12.769 › Detected 70 events from listener
12:30:13.269 › Detected 19 events from listener
12:30:13.771 › Detected 231 events from listener
12:30:14.269 › Detected 15 events from listener
12:30:14.869 › Detected 2 events from listener
12:30:15.370 › Detected 38 events from listener
12:30:15.870 › Detected 28 events from listener
12:30:16.370 › Detected 16 events from listener
12:30:17.621 › Detected 2 events from listener
12:30:18.121 › Detected 21 events from listener
12:30:19.573 › Detected 1 events from listener
12:30:20.073 › Detected 9 events from listener
12:30:20.573 › Detected 31 events from listener
12:30:21.073 › Detected 11 events from listener
12:30:21.623 › Detected 8 events from listener
12:30:22.123 › Detected 4 events from listener
12:30:22.624 › Detected 13 events from listener
12:30:23.124 › Detected 67 events from listener
12:30:23.624 › Detected 132 events from listener
12:30:24.124 › Detected 77 events from listener
12:30:24.624 › Detected 108 events from listener
12:30:25.124 › Detected 244 events from listener
12:30:25.624 › Detected 112 events from listener
12:30:26.125 › Detected 280 events from listener
12:30:26.624 › Detected 86 events from listener
12:30:27.124 › Detected 114 events from listener
12:30:27.624 › Detected 61 events from listener
12:30:28.124 › Detected 32 events from listener
12:30:28.624 › Detected 10 events from listener
12:30:29.125 › Detected 16 events from listener
12:30:29.675 › Detected 1 events from listener
12:30:30.175 › Detected 5 events from listener
12:30:30.675 › Detected 1 events from listener
12:30:31.175 › Detected 139 events from listener
12:30:31.675 › Detected 39 events from listener
12:30:32.175 › Detected 68 events from listener
12:30:32.676 › Detected 31 events from listener
12:30:33.175 › Detected 26 events from listener
12:30:33.675 › Detected 2 events from listener
12:30:34.176 › Detected 1 events from listener
12:30:34.676 › Detected 1 events from listener
12:30:35.176 › Detected 20 events from listener
12:30:35.676 › Detected 82 events from listener
12:30:36.176 › Detected 43 events from listener
12:30:36.676 › Detected 15 events from listener
12:30:37.176 › Detected 2 events from listener
12:30:37.676 › Detected 5 events from listener
12:30:38.177 › Detected 36 events from listener
12:30:38.677 › Detected 2 events from listener
12:30:39.177 › Detected 202 events from listener
12:30:39.677 › Detected 61 events from listener
12:30:40.177 › Detected 13 events from listener
12:30:41.578 › Detected 1 events from listener
12:30:42.079 › Detected 4 events from listener
12:30:42.629 › Detected 16 events from listener
12:30:43.129 › Detected 62 events from listener
12:30:43.629 › Detected 36 events from listener
12:30:44.129 › Detected 10 events from listener
12:30:44.629 › Detected 7 events from listener
12:30:45.129 › Detected 76 events from listener
12:30:45.630 › Detected 80 events from listener
12:30:46.129 › Detected 2 events from listener
12:30:46.980 › Detected 2 events from listener
12:30:47.480 › Detected 8 events from listener
12:30:47.980 › Detected 30 events from listener
12:30:48.480 › Detected 22 events from listener
12:30:48.980 › Detected 9 events from listener
12:30:50.391 › Detected 1 events from listener
12:30:50.891 › Detected 3 events from listener
12:30:51.641 › Detected 2 events from listener
12:30:52.141 › Detected 2 events from listener
12:30:52.641 › Detected 8 events from listener
12:30:53.842 › Detected 11 events from listener
12:30:54.343 › Detected 27 events from listener
12:30:55.243 › Detected 4 events from listener
12:30:55.743 › Detected 46 events from listener
12:30:56.794 › Detected 1 events from listener
12:30:57.294 › Detected 26 events from listener
12:30:57.794 › Detected 14 events from listener
12:30:58.295 › Detected 38 events from listener
12:30:58.795 › Detected 32 events from listener
12:30:59.295 › Detected 123 events from listener
12:30:59.795 › Detected 33 events from listener
12:31:00.295 › Detected 3 events from listener
12:31:00.795 › Detected 7 events from listener
12:31:02.246 › Detected 3 events from listener
12:31:02.747 › Detected 38 events from listener
12:31:04.849 › Detected 4 events from listener
12:31:05.349 › Detected 62 events from listener
12:31:05.849 › Detected 4 events from listener
12:31:06.399 › Detected 3 events from listener
12:31:06.899 › Detected 1 events from listener
12:31:07.400 › Detected 54 events from listener
12:31:07.900 › Detected 115 events from listener
12:31:12.756 › Detected 11 events from listener
12:31:13.256 › Detected 15 events from listener
12:31:13.756 › Detected 1 events from listener
12:31:14.256 › Detected 3 events from listener
12:31:14.757 › Detected 3 events from listener
12:31:15.257 › Detected 2 events from listener
12:31:15.757 › Detected 1 events from listener
12:31:34.486 › Detected 1 events from listener
12:31:35.687 › Detected 2 events from listener
12:31:36.688 › Detected 1 events from listener
12:31:37.189 › Detected 230 events from listener
12:31:37.688 › Detected 113 events from listener
12:31:38.188 › Detected 2 events from listener
12:31:38.688 › Detected 1 events from listener
12:31:39.188 › Detected 2 events from listener
12:31:39.688 › Detected 1 events from listener
12:31:40.188 › Detected 1 events from listener
12:31:59.868 › Detected 1 events from listener
12:32:02.271 › Detected 3 events from listener
12:32:05.525 › Detected 1 events from listener
12:32:06.125 › Detected 1 events from listener
12:32:06.625 › Detected 1 events from listener
12:32:07.125 › Detected 2 events from listener
12:32:07.926 › Detected 1 events from listener
12:32:29.760 › Detected 1 events from listener
12:32:37.071 › Detected 1 events from listener
12:32:37.571 › Detected 1 events from listener
12:32:46.485 › Detected 1 events from listener
12:33:02.260 › Detected 3 events from listener
12:33:07.118 › Detected 1 events from listener
12:33:08.870 › Detected 1 events from listener
12:33:26.997 › Detected 1 events from listener
12:33:37.063 › Detected 1 events from listener
12:33:37.563 › Detected 1 events from listener
12:33:44.924 › Detected 1 events from listener
12:34:02.251 › Detected 3 events from listener
12:34:10.463 › Detected 1 events from listener
12:34:37.306 › Detected 1 events from listener
12:34:37.806 › Detected 1 events from listener
12:34:47.922 › Detected 1 events from listener
12:34:59.742 › Detected 1 events from listener
12:35:02.245 › Detected 3 events from listener
12:35:09.957 › Detected 1 events from listener
12:35:13.562 › Detected 1 events from listener
12:35:29.587 › Detected 1 events from listener
12:35:37.349 › Detected 1 events from listener
12:35:48.817 › Detected 1 events from listener
