### ISSUE TITLE
can't install NPM dependencies

### ISSUE THREAD

**Issue by cobalt2727** [killpowa/Twickt-Launcher#1325]
**Describe the bug**

**To Reproduce**
1. have NodeJS 18 installed from NodeSource
2. `git clone https://gorilla-devs/GDLauncher`
3. `cd GDLauncher`
4. `npm i`

**Expected behavior**
dependencies installing

**Operating System:**
- OS: Pop!_OS
- Version: 22.04
- Java Version: OpenJDK 17.0.3, not that it matters

**Logs:**
`cobalt@cobalt-inspiron:~/GDLauncher$ npm i`
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: craco-antd@1.19.0
npm ERR! Found: @craco/craco@6.4.3
npm ERR! node_modules/@craco/craco
npm ERR!   dev @craco/craco@"^6.4.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @craco/craco@"^5.5.0" from craco-antd@1.19.0
npm ERR! node_modules/craco-antd
npm ERR!   craco-antd@"^1.19.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @craco/craco@5.9.0
npm ERR! node_modules/@craco/craco
npm ERR!   peer @craco/craco@"^5.5.0" from craco-antd@1.19.0
npm ERR!   node_modules/craco-antd
npm ERR!     craco-antd@"^1.19.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/cobalt/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cobalt/.npm/_logs/2022-05-04T01_15_27_299Z-debug-0.log
```
`cobalt@cobalt-inspiron:~/GDLauncher$ cat /home/cobalt/.npm/eresolve-report.txt`
```bash
# npm resolution error report

2022-05-04T01:15:29.984Z

While resolving: craco-antd@1.19.0
Found: @craco/craco@6.4.3
node_modules/@craco/craco
  dev @craco/craco@"^6.4.3" from the root project

Could not resolve dependency:
peer @craco/craco@"^5.5.0" from craco-antd@1.19.0
node_modules/craco-antd
  craco-antd@"^1.19.0" from the root project

Conflicting peer dependency: @craco/craco@5.9.0
node_modules/@craco/craco
  peer @craco/craco@"^5.5.0" from craco-antd@1.19.0
  node_modules/craco-antd
    craco-antd@"^1.19.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "edge": {
    "type": "peer",
    "name": "@craco/craco",
    "spec": "^5.5.0",
    "error": "INVALID",
    "from": {
      "name": "craco-antd",
      "version": "1.19.0",
      "location": "node_modules/craco-antd",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "craco-antd",
          "spec": "^1.19.0",
          "from": {
            "location": "/home/cobalt/GDLauncher"
          }
        }
      ]
    }
  },
  "dep": {
    "name": "@craco/craco",
    "version": "5.9.0",
    "whileInstalling": {
      "name": "craco-antd",
      "version": "1.19.0",
      "path": "/home/cobalt/GDLauncher/node_modules/craco-antd"
    },
    "location": "node_modules/@craco/craco",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "peer",
        "name": "@craco/craco",
        "spec": "^5.5.0",
        "error": "INVALID",
        "from": {
          "name": "craco-antd",
          "version": "1.19.0",
          "location": "node_modules/craco-antd",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "prod",
              "name": "craco-antd",
              "spec": "^1.19.0",
              "from": {
                "location": "/home/cobalt/GDLauncher"
              }
            }
          ]
        }
      }
    ]
  },
  "current": {
    "name": "@craco/craco",
    "version": "6.4.3",
    "location": "node_modules/@craco/craco",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "dev",
        "name": "@craco/craco",
        "spec": "^6.4.3",
        "from": {
          "location": "/home/cobalt/GDLauncher"
        }
      }
    ]
  },
  "peerConflict": {
    "current": {
      "name": "@craco/craco",
      "version": "6.4.3",
      "location": "node_modules/@craco/craco",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "dev",
          "name": "@craco/craco",
          "spec": "^6.4.3",
          "from": {
            "location": "/home/cobalt/GDLauncher"
          }
        }
      ]
    },
    "peer": {
      "name": "@craco/craco",
      "version": "5.9.0",
      "whileInstalling": {
        "name": "craco-antd",
        "version": "1.19.0",
        "path": "/home/cobalt/GDLauncher/node_modules/craco-antd"
      },
      "location": "node_modules/@craco/craco",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peer",
          "name": "@craco/craco",
          "spec": "^5.5.0",
          "error": "INVALID",
          "from": {
            "name": "craco-antd",
            "version": "1.19.0",
            "location": "node_modules/craco-antd",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "prod",
                "name": "craco-antd",
                "spec": "^1.19.0",
                "from": {
                  "location": "/home/cobalt/GDLauncher"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false,
  "isMine": true
}
```
`cobalt@cobalt-inspiron:~/GDLauncher$ cat /home/cobalt/.npm/_logs/2022-05-04T01_15_27_299Z-debug-0.log`
```bash
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.8.0
2 info using node@v18.1.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/cobalt/GDLauncher/.npmrc Completed in 1ms
10 timing config:load:project Completed in 9ms
11 timing config:load:file:/home/cobalt/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 16ms
19 timing npm:load:configload Completed in 16ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i
23 verbose argv "i"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:/home/cobalt/.npm/_logs
28 verbose logfile /home/cobalt/.npm/_logs/2022-05-04T01_15_27_299Z-debug-0.log
29 timing npm:load:logFile Completed in 5ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 27ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 2079ms
37 timing idealTree:userRequests Completed in 0ms
38 silly idealTree buildDeps
39 timing idealTree:#root Completed in 1ms
40 silly fetch manifest @babel/core@^7.13.0
41 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 28ms (cache hit)
42 silly placeDep ROOT @babel/core@7.17.10 REPLACE for: @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5 want: ^7.13.0
43 silly fetch manifest @ampproject/remapping@^2.1.0
44 silly fetch manifest @babel/code-frame@^7.16.7
45 silly fetch manifest @babel/generator@^7.17.10
46 silly fetch manifest @babel/helper-compilation-targets@^7.17.10
47 silly fetch manifest @babel/helper-module-transforms@^7.17.7
48 silly fetch manifest @babel/helpers@^7.17.9
49 silly fetch manifest @babel/parser@^7.17.10
50 silly fetch manifest @babel/template@^7.16.7
51 silly fetch manifest @babel/traverse@^7.17.10
52 silly fetch manifest @babel/types@^7.17.10
53 silly fetch manifest json5@^2.2.1
54 silly fetch manifest semver@^6.3.0
55 http fetch GET 200 https://registry.npmjs.org/@babel%2fcode-frame 25ms (cache hit)
56 http fetch GET 200 https://registry.npmjs.org/@ampproject%2fremapping 26ms (cache hit)
57 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-compilation-targets 26ms (cache hit)
58 http fetch GET 200 https://registry.npmjs.org/@babel%2fparser 26ms (cache hit)
59 http fetch GET 200 https://registry.npmjs.org/@babel%2fgenerator 28ms (cache hit)
60 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelpers 30ms (cache hit)
61 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-module-transforms 31ms (cache hit)
62 http fetch GET 200 https://registry.npmjs.org/@babel%2ftemplate 31ms (cache hit)
63 http fetch GET 200 https://registry.npmjs.org/json5 31ms (cache hit)
64 http fetch GET 200 https://registry.npmjs.org/semver 33ms (cache hit)
65 http fetch GET 200 https://registry.npmjs.org/@babel%2ftypes 36ms (cache hit)
66 http fetch GET 200 https://registry.npmjs.org/@babel%2ftraverse 38ms (cache hit)
67 timing idealTree:node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining Completed in 165ms
68 silly fetch manifest @babel/core@^7.0.0
69 silly placeDep ROOT @ampproject/remapping@2.2.0 OK for: @babel/core@7.17.10 want: ^2.1.0
70 silly placeDep ROOT @babel/code-frame@7.16.7 REPLACE for: @babel/core@7.17.10 want: ^7.16.7
71 silly placeDep ROOT @babel/generator@7.17.10 REPLACE for: @babel/core@7.17.10 want: ^7.17.10
72 silly placeDep ROOT @babel/helper-compilation-targets@7.17.10 REPLACE for: @babel/core@7.17.10 want: ^7.17.10
73 silly placeDep ROOT @babel/helper-module-transforms@7.17.7 REPLACE for: @babel/core@7.17.10 want: ^7.17.7
74 silly placeDep ROOT @babel/helpers@7.17.9 OK for: @babel/core@7.17.10 want: ^7.17.9
75 silly placeDep ROOT @babel/parser@7.17.10 REPLACE for: @babel/core@7.17.10 want: ^7.17.10
76 silly placeDep ROOT @babel/template@7.16.7 REPLACE for: @babel/core@7.17.10 want: ^7.16.7
77 silly placeDep ROOT @babel/traverse@7.17.10 REPLACE for: @babel/core@7.17.10 want: ^7.17.10
78 silly placeDep ROOT @babel/types@7.17.10 REPLACE for: @babel/core@7.17.10 want: ^7.17.10
79 silly placeDep ROOT json5@2.2.1 REPLACE for: @babel/core@7.17.10 want: ^2.2.1
80 silly placeDep node_modules/@babel/core semver@6.3.0 OK for: @babel/core@7.17.10 want: ^6.3.0
81 silly fetch manifest @jridgewell/gen-mapping@^0.1.0
82 silly fetch manifest @jridgewell/trace-mapping@^0.3.9
83 silly fetch manifest @babel/highlight@^7.16.7
84 silly fetch manifest @babel/compat-data@^7.17.10
85 silly fetch manifest @babel/helper-validator-option@^7.16.7
86 silly fetch manifest browserslist@^4.20.2
87 silly fetch manifest @babel/helper-environment-visitor@^7.16.7
88 silly fetch manifest @babel/helper-module-imports@^7.16.7
89 silly fetch manifest @babel/helper-simple-access@^7.17.7
90 silly fetch manifest @babel/helper-split-export-declaration@^7.16.7
91 silly fetch manifest @babel/helper-validator-identifier@^7.16.7
92 silly fetch manifest @babel/helper-function-name@^7.17.9
93 silly fetch manifest @babel/helper-hoist-variables@^7.16.7
94 http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fgen-mapping 27ms (cache hit)
95 http fetch GET 200 https://registry.npmjs.org/@babel%2fhighlight 27ms (cache hit)
96 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-module-imports 27ms (cache hit)
97 http fetch GET 200 https://registry.npmjs.org/@babel%2fcompat-data 28ms (cache hit)
98 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-split-export-declaration 27ms (cache hit)
99 http fetch GET 200 https://registry.npmjs.org/@jridgewell%2ftrace-mapping 30ms (cache hit)
100 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-validator-option 29ms (cache hit)
101 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-simple-access 29ms (cache hit)
102 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-validator-identifier 28ms (cache hit)
103 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-hoist-variables 28ms (cache hit)
104 http fetch GET 200 https://registry.npmjs.org/browserslist 32ms (cache hit)
105 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-function-name 32ms (cache hit)
106 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-environment-visitor 35ms (cache hit)
107 timing idealTree:node_modules/@babel/core Completed in 89ms
108 silly placeDep ROOT @jridgewell/gen-mapping@0.1.1 OK for: @ampproject/remapping@2.2.0 want: ^0.1.0
109 silly placeDep ROOT @jridgewell/trace-mapping@0.3.9 OK for: @ampproject/remapping@2.2.0 want: ^0.3.9
110 silly fetch manifest @jridgewell/set-array@^1.0.0
111 silly fetch manifest @jridgewell/sourcemap-codec@^1.4.10
112 silly fetch manifest @jridgewell/resolve-uri@^3.0.3
113 http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fsourcemap-codec 6ms (cache hit)
114 http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fset-array 7ms (cache hit)
115 http fetch GET 200 https://registry.npmjs.org/@jridgewell%2fresolve-uri 5ms (cache hit)
116 timing idealTree:node_modules/@ampproject/remapping Completed in 14ms
117 silly placeDep ROOT @babel/highlight@7.17.9 REPLACE for: @babel/code-frame@7.16.7 want: ^7.16.7
118 timing idealTree:node_modules/@babel/code-frame Completed in 3ms
119 timing idealTree:node_modules/@babel/generator Completed in 0ms
120 silly placeDep ROOT @babel/compat-data@7.17.10 REPLACE for: @babel/helper-compilation-targets@7.17.10 want: ^7.17.10
121 silly placeDep ROOT @babel/helper-validator-option@7.16.7 REPLACE for: @babel/helper-compilation-targets@7.17.10 want: ^7.16.7
122 silly placeDep ROOT browserslist@4.20.3 REPLACE for: @babel/helper-compilation-targets@7.17.10 want: ^4.20.2
123 silly fetch manifest caniuse-lite@^1.0.30001332
124 silly fetch manifest electron-to-chromium@^1.4.118
125 silly fetch manifest node-releases@^2.0.3
126 http fetch GET 200 https://registry.npmjs.org/node-releases 10ms (cache hit)
127 http fetch GET 200 https://registry.npmjs.org/caniuse-lite 14ms (cache hit)
128 http fetch GET 200 https://registry.npmjs.org/electron-to-chromium 19ms (cache hit)
129 timing idealTree:node_modules/@babel/helper-compilation-targets Completed in 40ms
130 timing idealTree:node_modules/@babel/compat-data Completed in 0ms
131 silly placeDep ROOT @babel/helper-environment-visitor@7.16.7 OK for: @babel/helper-module-transforms@7.17.7 want: ^7.16.7
132 silly placeDep ROOT @babel/helper-module-imports@7.16.7 REPLACE for: @babel/helper-module-transforms@7.17.7 want: ^7.16.7
133 silly placeDep ROOT @babel/helper-simple-access@7.17.7 REPLACE for: @babel/helper-module-transforms@7.17.7 want: ^7.17.7
134 silly placeDep ROOT @babel/helper-split-export-declaration@7.16.7 REPLACE for: @babel/helper-module-transforms@7.17.7 want: ^7.16.7
135 silly placeDep ROOT @babel/helper-validator-identifier@7.16.7 REPLACE for: @babel/helper-module-transforms@7.17.7 want: ^7.16.7
136 timing idealTree:node_modules/@babel/helper-module-transforms Completed in 19ms
137 timing idealTree:node_modules/@babel/helper-environment-visitor Completed in 0ms
138 timing idealTree:node_modules/@babel/helper-module-imports Completed in 0ms
139 timing idealTree:node_modules/@babel/helper-simple-access Completed in 0ms
140 timing idealTree:node_modules/@babel/helper-split-export-declaration Completed in 0ms
141 timing idealTree:node_modules/@babel/helper-validator-identifier Completed in 0ms
142 timing idealTree:node_modules/@babel/helper-validator-option Completed in 0ms
143 timing idealTree:node_modules/@babel/helpers Completed in 0ms
144 timing idealTree:node_modules/@babel/highlight Completed in 0ms
145 timing idealTree:node_modules/@babel/parser Completed in 0ms
146 timing idealTree:node_modules/@babel/template Completed in 0ms
147 silly placeDep ROOT @babel/helper-function-name@7.17.9 REPLACE for: @babel/traverse@7.17.10 want: ^7.17.9
148 silly placeDep ROOT @babel/helper-hoist-variables@7.16.7 REPLACE for: @babel/traverse@7.17.10 want: ^7.16.7
149 timing idealTree:node_modules/@babel/traverse Completed in 7ms
150 timing idealTree:node_modules/@babel/helper-function-name Completed in 0ms
151 timing idealTree:node_modules/@babel/helper-hoist-variables Completed in 0ms
152 timing idealTree:node_modules/@babel/types Completed in 0ms
153 silly placeDep ROOT @jridgewell/set-array@1.1.0 OK for: @jridgewell/gen-mapping@0.1.1 want: ^1.0.0
154 silly placeDep ROOT @jridgewell/sourcemap-codec@1.4.12 OK for: @jridgewell/gen-mapping@0.1.1 want: ^1.4.10
155 timing idealTree:node_modules/@jridgewell/gen-mapping Completed in 5ms
156 timing idealTree:node_modules/@jridgewell/set-array Completed in 0ms
157 timing idealTree:node_modules/@jridgewell/sourcemap-codec Completed in 0ms
158 silly placeDep ROOT @jridgewell/resolve-uri@3.0.6 OK for: @jridgewell/trace-mapping@0.3.9 want: ^3.0.3
159 timing idealTree:node_modules/@jridgewell/trace-mapping Completed in 3ms
160 timing idealTree:node_modules/@jridgewell/resolve-uri Completed in 0ms
161 silly fetch manifest type-fest@^0.13.1
162 http fetch GET 200 https://registry.npmjs.org/type-fest 7ms (cache hit)
163 silly placeDep ROOT type-fest@0.13.1 REPLACE for: @pmmmwh/react-refresh-webpack-plugin@0.4.3 want: ^0.13.1
164 timing idealTree:node_modules/@pmmmwh/react-refresh-webpack-plugin Completed in 15ms
165 silly fetch manifest @babel/core@7.12.3
166 silly placeDep node_modules/babel-preset-react-app @babel/core@7.12.3 OK for: babel-preset-react-app@10.0.0 want: 7.12.3
167 silly fetch manifest source-map@^0.5.0
168 http fetch GET 200 https://registry.npmjs.org/source-map 3ms (cache hit)
169 timing idealTree:node_modules/babel-preset-react-app Completed in 13ms
170 silly placeDep ROOT caniuse-lite@1.0.30001335 REPLACE for: browserslist@4.20.3 want: ^1.0.30001332
171 silly placeDep ROOT electron-to-chromium@1.4.132 REPLACE for: browserslist@4.20.3 want: ^1.4.118
172 silly placeDep node_modules/browserslist node-releases@2.0.4 OK for: browserslist@4.20.3 want: ^2.0.3
173 timing idealTree:node_modules/browserslist Completed in 13ms
174 timing idealTree:node_modules/caniuse-lite Completed in 0ms
175 silly fetch manifest @craco/craco@^5.5.0
176 http fetch GET 200 https://registry.npmjs.org/@craco%2fcraco 3ms (cache hit)
177 silly fetch manifest react-scripts@^3.4.3
178 http fetch GET 200 https://registry.npmjs.org/react-scripts 3ms (cache hit)
179 silly fetch manifest typescript@^3.2.1
180 http fetch GET 200 https://registry.npmjs.org/typescript 15ms (cache hit)
181 timing idealTree Completed in 2573ms
182 timing command:i Completed in 2584ms
183 verbose stack Error: could not resolve
183 verbose stack     at PlaceDep.failPeerConflict (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:549:25)
183 verbose stack     at PlaceDep.place (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:199:21)
183 verbose stack     at new PlaceDep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
183 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:988:31
183 verbose stack     at Array.map (<anonymous>)
183 verbose stack     at [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:988:8)
183 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
183 verbose stack     at async Promise.all (index 1)
183 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
183 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:156:5)
184 verbose cwd /home/cobalt/GDLauncher
185 verbose Linux 5.16.19-76051619-generic
186 verbose node v18.1.0
187 verbose npm  v8.8.0
188 error code ERESOLVE
189 error ERESOLVE could not resolve
190 error
191 error While resolving: craco-antd@1.19.0
191 error Found: @craco/craco@6.4.3
191 error node_modules/@craco/craco
191 error   dev @craco/craco@"^6.4.3" from the root project
191 error
191 error Could not resolve dependency:
191 error peer @craco/craco@"^5.5.0" from craco-antd@1.19.0
191 error node_modules/craco-antd
191 error   craco-antd@"^1.19.0" from the root project
191 error
191 error Conflicting peer dependency: @craco/craco@5.9.0
191 error node_modules/@craco/craco
191 error   peer @craco/craco@"^5.5.0" from craco-antd@1.19.0
191 error   node_modules/craco-antd
191 error     craco-antd@"^1.19.0" from the root project
191 error
191 error Fix the upstream dependency conflict, or retry
191 error this command with --force, or --legacy-peer-deps
191 error to accept an incorrect (and potentially broken) dependency resolution.
191 error
191 error See /home/cobalt/.npm/eresolve-report.txt for a full report.
192 verbose exit 1
193 timing npm Completed in 2688ms
194 verbose unfinished npm timer reify 1651626927398
195 verbose unfinished npm timer reify:loadTrees 1651626927406
196 verbose unfinished npm timer idealTree:buildDeps 1651626929486
197 verbose unfinished npm timer idealTree:node_modules/craco-antd 1651626929874
198 verbose code 1
199 error A complete log of this run can be found in:
199 error     /home/cobalt/.npm/_logs/2022-05-04T01_15_27_299Z-debug-0.log
```

**Comment by Eskaan** [comment]
I think some dependencies were marked deprecated…
Edit: Yeah I checked. We still use node version 14.

**Comment by cobalt2727** [comment]
@Eskaan this is still an issue, can someone look at getting https://github.com/gorilla-devs/GDLauncher/pull/1462 merged?

I should also note that `npm i --legacy-peer-deps` _does_ work correctly

**Comment by Eskaan** [comment]
It is indeed still an issue. We have gotten ourselves a pretty bad dependency resolution that does not allow us to update.

**Comment by cobalt2727** [comment]
is the PR mentioned a viable fix in the meantime? or at the very least, just updating the build instructions to include `--legacy-peer-deps`
