### ISSUE TITLE
The GDLauncher does not launch.

### ISSUE THREAD

**Issue by AlexFwfwfw1** [killpowa/Twickt-Launcher#1362]
I installed GDLanucher with the command:
"sudo snap install gdlauncher --beta".
When I try to launch it, well.. it does not.

**To Reproduce**
1. Install via  'sudo snap install gdlauncher --beta'
2. Click on 'GDLauncher' icon on Ubuntu Menu
3. Wait to not launch.

**Expected behavior**
To launch

**Possible solutions**
None

**Screenshots**
None

**Operating System:**
- OS: Ubuntu 
- Version: 22.04 LTS 
- Java Version: 11.0.15
- Minecraft Version: Not Important
- Mod Loader: Not Important

**Additional context**
Before, I installed Minecraft Launcher of the Minecraft official website. Do not know if that changes anything.

**Comment by Eskaan** [comment]
Can you download the .deb from the releases manually and try that?

**Comment by StephenWelch** [comment]
Can confirm the .deb release doesn't launch on Ubuntu 20.04.4. The AppImage installer gives this error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/native/linux/murmur2.node: Error: /tmp/.org.chromium.Chromium.JWnlJr: failed to map segment from shared object
    at Object.<anonymous> (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:2441036)
    at ./public/native/linux/murmur2.node (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:2441074)
    at i (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:124)
    at ./public/native/murmur2.js (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:2441571)
    at i (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:124)
    at ./public/electron.js (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:2428177)
    at i (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:124)
    at module.exports../node_modules/base64url/dist/base64url.js (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:923)
    at Object.<anonymous> (/tmp/.mount_GDLaun2JG6pr/resources/app.asar/build/electron.js:2:953)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
```
The snap release worked for me, but it doesn't support Microsoft logins so I can't use it. So probably two separate issues.

**Comment by Eskaan** [comment]
Which version of GDL is this?

**Comment by teambob** [comment]
The Ubuntu snap store version is 0.10.3 and doesn't work. The AppImage and deb worked for me on Ubuntu 22.04 LTS

Perhaps the devs can update the snap with the latest version?

**Comment by Eskaan** [comment]
We don't maintain the Snap version ourselves, you'll have to ask the maintainer for the package over on the Ubuntu repositories.
