### ISSUE TITLE
Clicking a link in minecraft chat does not open the browser (Fedora Linux - Gnome)

### ISSUE THREAD

**Issue by socksprox** [killpowa/Twickt-Launcher#1445]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)
Not sure if minecraft or launcher issue, if it's an mc issue, just close the report
**Describe the bug**
Clicking a link in the minecraft chat, does not open the browser (after clicking on okay) i can only copy and t hen paste in the browser

**To Reproduce**
- Make sure to use linux
- Click a link in mc chat and then on ok
- A browser window won't open/no new tab

**Expected behavior**
Browser window with the site should've opened

**Possible solutions**
Maybe some fault linking stuff on GD's side? Not sure though

**Operating System:**
- OS: Linux (Fedora)
- Launcher Version: 1.1.29
- Java Version: Installed suggested ones from GdLauncher
- Minecraft Version: 1.19.2
- Mod Loader: Fabric

**Comment by Eskaan** [comment]
Can you try reproducing the error with another Launcher (like PolyMC, MultiMC, the Native Launcher, ATLauncher)? If it doesn't happen there it's definitely Launcher-related.

Edit: 
Otherwise it may be a problem with Fedora not recognizing the signal Minecraft/Java sends.
I currently have a similar problem with Discord on my Arch Linux install that requires me to have the Browser opened before clicking the link, is it the same for you or is there just no reaction whatever you do?
You could check the launcher console for any messages that get printed when you click a link (>_ at the top, console tab), that would be great.

**Comment by socksprox** [comment]
> Can you try reproducing the error with another Launcher (like PolyMC, MultiMC, the Native Launcher, ATLauncher)? If it doesn't happen there it's definitely Launcher-related.
> 
> Edit: Otherwise it may be a problem with Fedora not recognizing the signal Minecraft/Java sends. I currently have a similar problem with Discord on my Arch Linux install that requires me to have the Browser opened before clicking the link, is it the same for you or is there just no reaction whatever you do? You could check the launcher console for any messages that get printed when you click a link (>_ at the top, console tab), that would be great.

Hmm, i can indeed click on it when using the official launcher...

**Comment by Zubbbz** [comment]
I also have this same issue, as well as things like the "Open Pack Folder" button in the resource packs menu. I am on arch (steamos) using the version of gdlauncher from Discover

**Comment by LordRaptorNinja** [comment]
> I also have this same issue, as well as things like the "Open Pack Folder" button in the resource packs menu. I am on arch (steamos) using the version of gdlauncher from Discover

That is happening to me to

**Comment by j-romchain** [comment]
this is also happening to me. I can provide logs if you want.

**Comment by Eskaan** [comment]
Yeah, logs would be really appreciated for this.

**Comment by j-romchain** [comment]
ok, I have 2 logs of the occurence here, both are from the same Minecraft instance, one is from the latest.log, and the other is from the console in GD, Ill put them in 2 different comments. first one will be the latest.log. I am just including the log of the events surrounding and including the failed opening, and it should be noted that I have vanilla compatible mods and one doesn't log an error (essential), but another (ingameaccountswitcher) does.

**Comment by j-romchain** [comment]
[12:15:22] [Worker-Cape-9/DEBUG]: Worker-Cape-9 shutdown
[12:15:25] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/firebugs, volume was zero.
[12:15:37] [Render thread/DEBUG]: Skipped playing sound minecraft:music/menu/menu1, volume was zero.
[12:15:38] [Render thread/DEBUG]: Playing sound minecraft:random/click_stereo for event minecraft:ui.button.click
[12:15:38] [IAS Executor/ERROR]: Couldn't open url 'https://login.live.com/oauth20_authorize.srf?client_id=54fd49e4-2103-4044-9603-2b028c814ec3&response_type=code&scope=XboxLive.signin%20XboxLive.offline_access&redirect_uri=http://localhost:59125&prompt=select_account'
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_669(class_156.java:1127) ~[client-intermediary.jar:?]
	at net.minecraft.class_156$class_158.method_670(class_156.java:1183) ~[client-intermediary.jar:?]
	at the_fireplace.ias.gui.LoginScreen.lambda$loginMicrosoft$10(LoginScreen.java:94) ~[InGameAccountSwitcher-Fabric-1.19-8.0.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: Cannot run program "xdg-open": error=13, Permission denied
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:1129) ~[client-intermediary.jar:?]
	... 7 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:?]
	at java.lang.ProcessImpl.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:1129) ~[client-intermediary.jar:?]
	... 7 more
[12:15:38] [IAS Executor/INFO]: Started Microsoft authentication callback server.
[12:15:38] [Worker-Main-5/DEBUG]: Worker-Main-5 shutdown
[12:15:39] [Render thread/DEBUG]: Removed channel net.minecraft.class_4235$class_4236@60cf876c because it's not playing anymore
[12:15:45] [Render thread/DEBUG]: Skipped playing sound minecraft:music/menu/menu2, volume was zero.
[12:16:05] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/aerie, volume was zero.
[12:16:10] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/aerie, volume was zero.
[12:16:26] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/firebugs, volume was zero.
[12:16:38] [Worker-Main-7/DEBUG]: Worker-Main-7 shutdown

**Comment by j-romchain** [comment]
[12:15:22] [Worker-Cape-9/DEBUG]: Worker-Cape-9 shutdown

actions.js:3272 [12:15:25] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/firebugs, volume was zero.

actions.js:3272 [12:15:37] [Render thread/DEBUG]: Skipped playing sound minecraft:music/menu/menu1, volume was zero.

actions.js:3272 [12:15:38] [Render thread/DEBUG]: Playing sound minecraft:random/click_stereo for event minecraft:ui.button.click

actions.js:3272 [12:15:38] [IAS Executor/ERROR]: Couldn't open url 'https://login.live.com/oauth20_authorize.srf?client_id=54fd49e4-2103-4044-9603-2b028c814ec3&response_type=code&scope=XboxLive.signin%20XboxLive.offline_access&redirect_uri=http://localhost:59125&prompt=select_account'
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_669(class_156.java:1127) ~[client-intermediary.jar:?]
	at net.minecraft.class_156$class_158.method_670(class_156.java:1183) ~[client-intermediary.jar:?]
	at the_fireplace.ias.gui.LoginScreen.lambda$loginMicrosoft$10(LoginScreen.java:94) ~[InGameAccountSwitcher-Fabric-1.19-8.0.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: Cannot run program "xdg-open": error=13, Permission denied
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:1129) ~[client-intermediary.jar:?]
	... 7 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:?]
	at java.lang.ProcessImpl.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at java.lang.Runtime.exec(Unknown Source) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:1129) ~[client-intermediary.jar:?]
	... 7 more

actions.js:3272 [12:15:38] [IAS Executor/INFO]: Started Microsoft authentication callback server.

actions.js:3272 [12:15:38] [Worker-Main-5/DEBUG]: Worker-Main-5 shutdown

actions.js:3272 [12:15:39] [Render thread/DEBUG]: Removed channel net.minecraft.class_4235$class_4236@60cf876c because it's not playing anymore

actions.js:3272 [12:15:45] [Render thread/DEBUG]: Skipped playing sound minecraft:music/menu/menu2, volume was zero.

actions.js:3272 [12:16:05] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/aerie, volume was zero.

actions.js:3272 [12:16:10] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/aerie, volume was zero.

actions.js:3272 [12:16:26] [Render thread/DEBUG]: Skipped playing sound minecraft:music/game/swamp/firebugs, volume was zero.

actions.js:3272 [12:16:38] [Worker-Main-7/DEBUG]: Worker-Main-7 shutdown

**Comment by j-romchain** [comment]
as I said, this is from a mod called ingameaccountswitcher, but it is probably the same basic error that keeps the vanilla chat from opening links and such properly. the other mod I mentioned, essential, also cannot open links, but the log only shows logs of the sounds played when pressing the buttons to open the link, nothing about it failing to open the link.

**Comment by j-romchain** [comment]
also, this is on Ubuntu 22.04.2 LTS 64-bit gnome 42.5 Wayland, with Google Chrome (beta) as my default browser, it shows the same error with non beta chrome. this is the complete modset for the logs:
3dskinlayers-fabric-1.5.2-mc1.19.1.jar
balm-fabric-1.19.2-4.5.7.jar
clienttweaks-fabric-1.19.2-8.1.2.jar
cloth-config-8.2.88-fabric.jar
effective-1.3.jar
entityculling-fabric-1.6.1-mc1.19.2.jar
essential_commands-0.33.0-mc1.19.2.jar
Essential-fabric_1-19.jar
fabric-api-0.76.0+1.19.2.jar
glowyplayers-1.0.0.jar
InGameAccountSwitcher-Fabric-1.19-8.0.1.jar
lazydfu-0.1.3.jar
litematica-fabric-1.19.2-0.12.5.jar
litematica-tool-1.0.0.jar
malilib-fabric-1.19.2-0.13.0.jar
modmenu-4.1.2.jar
NoChatReports-FABRIC-1.19.2-v1.13.12.jar
optifabric-1.13.16.jar
OptiFine_1.19.2_HD_U_H9.jar
plasmovoice-fabric-1.19.2-2.0.3.jar
skin-swapper-fabric-3.1.2.jar
starlight-1.1.1+fabric.ae22326.jar
ViaBackwards-4.6.1.jar
viafabric-0.4.9+19-main.jar
viafabric-0.4.9+21-main.jar
Xaeros_Minimap_23.4.1_Fabric_1.19.1.jar
XaerosWorldMap_1.30.1_Fabric_1.19.1.jar

and file .minecraft/instances/(instance)/debugsettings.xml saying "<?xml version="1.0" encoding="UTF-8"?>

<Configuration status="WARN" packages="net.minecraft,com.mojang">

    <Appenders>

        <Console name="SysOut" target="SYSTEM_OUT">

            <PatternLayout pattern="[%d{HH:mm:ss}] [%t/%level]: %msg%n" />

        </Console>

        <Queue name="ServerGuiConsole">

            <PatternLayout pattern="[%d{HH:mm:ss} %level]: %msg%n" />

        </Queue>

        <RollingRandomAccessFile name="File" fileName="logs/latest.log" filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz">

            <PatternLayout pattern="[%d{HH:mm:ss}] [%t/%level]: %msg%n" />

            <Policies>

                <TimeBasedTriggeringPolicy />

                <OnStartupTriggeringPolicy />

            </Policies>

        </RollingRandomAccessFile>

    </Appenders>

    <Loggers>

        <Root level="debug">

            <filters>

                <MarkerFilter marker="NETWORK_PACKETS" onMatch="ACCEPT" onMismatch="NEUTRAL" />

            </filters>

            <AppenderRef ref="SysOut"/>

            <AppenderRef ref="File"/>

            <AppenderRef ref="ServerGuiConsole"/>

        </Root>

    </Loggers> 

</Configuration>" and an extra argument of "-Dlog4j.configurationFile=debugsettings.xml"
